-- Doplnění zranění/kostek u kouzel, kde je popis textově popisuje, ale
-- strukturované sloupce (pocet_kostek/typ_kostky/pevny_bonus, migrace 0003)
-- zůstaly po importu prázdné. Vygenerováno strojově: rozsah v popisu ("1–6
-- životů", "2 až 7 životů"...) převeden na kostky přesně podle algoritmu
-- z pravidel (content/pravidla-hrac.html — diff=5*N -> Nk6, diff=9*N -> Nk10,
-- bonus = dolní mez - N). U vícenásobných efektů ("za blesk"/"za kolo"...)
-- nastaveno i vicenasobne=1. Každý řádek má trojitou pojistku: WHERE id + nazev
-- (kdyby se ID mezi seed souborem a produkcí rozešlo) + pocet_kostek IS NULL
-- (nikdy nepřepíše ručně už doplněnou/opravenou hodnotu).

UPDATE kouzla SET pocet_kostek=1, typ_kostky='k6', pevny_bonus=0, vicenasobne=0 WHERE id=3 AND nazev='Hyperprostor' AND pocet_kostek IS NULL;
UPDATE kouzla SET pocet_kostek=1, typ_kostky='k6', pevny_bonus=0, vicenasobne=0 WHERE id=8 AND nazev='Melenina krása' AND pocet_kostek IS NULL;
UPDATE kouzla SET pocet_kostek=1, typ_kostky='k6', pevny_bonus=0, vicenasobne=1 WHERE id=10 AND nazev='Modré blesky' AND pocet_kostek IS NULL;
UPDATE kouzla SET pocet_kostek=1, typ_kostky='k6', pevny_bonus=4, vicenasobne=0 WHERE id=13 AND nazev='Nebezpečné ovoce' AND pocet_kostek IS NULL;
UPDATE kouzla SET pocet_kostek=1, typ_kostky='k6', pevny_bonus=0, vicenasobne=0 WHERE id=16 AND nazev='Ohnivý déšť' AND pocet_kostek IS NULL;
UPDATE kouzla SET pocet_kostek=2, typ_kostky='k6', pevny_bonus=0, vicenasobne=1 WHERE id=26 AND nazev='Zelené blesky' AND pocet_kostek IS NULL;
UPDATE kouzla SET pocet_kostek=3, typ_kostky='k6', pevny_bonus=0, vicenasobne=0 WHERE id=35 AND nazev='Bílá střela' AND pocet_kostek IS NULL;
UPDATE kouzla SET pocet_kostek=1, typ_kostky='k6', pevny_bonus=0, vicenasobne=0 WHERE id=36 AND nazev='Bílý blesk' AND pocet_kostek IS NULL;
UPDATE kouzla SET pocet_kostek=3, typ_kostky='k6', pevny_bonus=38, vicenasobne=0 WHERE id=43 AND nazev='Černý blesk' AND pocet_kostek IS NULL;
UPDATE kouzla SET pocet_kostek=1, typ_kostky='k6', pevny_bonus=0, vicenasobne=0 WHERE id=58 AND nazev='Ohnivá koule' AND pocet_kostek IS NULL;
UPDATE kouzla SET pocet_kostek=1, typ_kostky='k6', pevny_bonus=0, vicenasobne=0 WHERE id=60 AND nazev='Ochrom bleskem' AND pocet_kostek IS NULL;
UPDATE kouzla SET pocet_kostek=1, typ_kostky='k10', pevny_bonus=0, vicenasobne=0 WHERE id=65 AND nazev='Přelož' AND pocet_kostek IS NULL;
UPDATE kouzla SET pocet_kostek=1, typ_kostky='k6', pevny_bonus=0, vicenasobne=0 WHERE id=67 AND nazev='Rozptyl kouzla' AND pocet_kostek IS NULL;
UPDATE kouzla SET pocet_kostek=5, typ_kostky='k6', pevny_bonus=0, vicenasobne=0 WHERE id=68 AND nazev='Rudé blesky' AND pocet_kostek IS NULL;
UPDATE kouzla SET pocet_kostek=4, typ_kostky='k10', pevny_bonus=0, vicenasobne=0 WHERE id=70 AND nazev='Zabij' AND pocet_kostek IS NULL;
UPDATE kouzla SET pocet_kostek=3, typ_kostky='k6', pevny_bonus=0, vicenasobne=0 WHERE id=72 AND nazev='Zmatek' AND pocet_kostek IS NULL;
UPDATE kouzla SET pocet_kostek=3, typ_kostky='k6', pevny_bonus=0, vicenasobne=0 WHERE id=74 AND nazev='Žluté blesky' AND pocet_kostek IS NULL;
UPDATE kouzla SET pocet_kostek=1, typ_kostky='k6', pevny_bonus=0, vicenasobne=0 WHERE id=77 AND nazev='Bílý blesk kulový' AND pocet_kostek IS NULL;
UPDATE kouzla SET pocet_kostek=9, typ_kostky='k6', pevny_bonus=96, vicenasobne=0 WHERE id=78 AND nazev='Bledý blesk' AND pocet_kostek IS NULL;
UPDATE kouzla SET pocet_kostek=9, typ_kostky='k6', pevny_bonus=96, vicenasobne=0 WHERE id=79 AND nazev='Bledý blesk kulový' AND pocet_kostek IS NULL;
UPDATE kouzla SET pocet_kostek=3, typ_kostky='k6', pevny_bonus=38, vicenasobne=0 WHERE id=81 AND nazev='Černý blesk kulový' AND pocet_kostek IS NULL;
UPDATE kouzla SET pocet_kostek=10, typ_kostky='k6', pevny_bonus=0, vicenasobne=0 WHERE id=87 AND nazev='Chlad hvězd' AND pocet_kostek IS NULL;
UPDATE kouzla SET pocet_kostek=4, typ_kostky='k10', pevny_bonus=0, vicenasobne=0 WHERE id=91 AND nazev='Ledový blesk' AND pocet_kostek IS NULL;
UPDATE kouzla SET pocet_kostek=3, typ_kostky='k6', pevny_bonus=0, vicenasobne=0 WHERE id=103 AND nazev='Ohnivý bič' AND pocet_kostek IS NULL;
UPDATE kouzla SET pocet_kostek=1, typ_kostky='k10', pevny_bonus=5, vicenasobne=0 WHERE id=107 AND nazev='Pekelný oheň' AND pocet_kostek IS NULL;
UPDATE kouzla SET pocet_kostek=1, typ_kostky='k6', pevny_bonus=0, vicenasobne=0 WHERE id=111 AND nazev='Portál' AND pocet_kostek IS NULL;
UPDATE kouzla SET pocet_kostek=1, typ_kostky='k6', pevny_bonus=1, vicenasobne=0 WHERE id=116 AND nazev='Přetvělení' AND pocet_kostek IS NULL;
UPDATE kouzla SET pocet_kostek=2, typ_kostky='k10', pevny_bonus=0, vicenasobne=1 WHERE id=119 AND nazev='Smrtící déšt' AND pocet_kostek IS NULL;
UPDATE kouzla SET pocet_kostek=1, typ_kostky='k6', pevny_bonus=0, vicenasobne=0 WHERE id=120 AND nazev='Smrtící koule' AND pocet_kostek IS NULL;
UPDATE kouzla SET pocet_kostek=1, typ_kostky='k6', pevny_bonus=0, vicenasobne=0 WHERE id=121 AND nazev='Soví oči' AND pocet_kostek IS NULL;
UPDATE kouzla SET pocet_kostek=1, typ_kostky='k10', pevny_bonus=0, vicenasobne=0 WHERE id=123 AND nazev='Sršatec' AND pocet_kostek IS NULL;
UPDATE kouzla SET pocet_kostek=1, typ_kostky='k6', pevny_bonus=0, vicenasobne=0 WHERE id=143 AND nazev='Zastrašení' AND pocet_kostek IS NULL;
UPDATE kouzla SET pocet_kostek=6, typ_kostky='k6', pevny_bonus=4, vicenasobne=0 WHERE id=145 AND nazev='Zmrzlý blesk' AND pocet_kostek IS NULL;
UPDATE kouzla SET pocet_kostek=1, typ_kostky='k4', pevny_bonus=0, vicenasobne=0 WHERE id=163 AND nazev='Zmrzlá země' AND pocet_kostek IS NULL;
UPDATE kouzla SET pocet_kostek=1, typ_kostky='k4', pevny_bonus=0, vicenasobne=0 WHERE id=164 AND nazev='Sněhová bouře' AND pocet_kostek IS NULL;
UPDATE kouzla SET pocet_kostek=1, typ_kostky='k6', pevny_bonus=2, vicenasobne=0 WHERE id=165 AND nazev='Permafrost' AND pocet_kostek IS NULL;
UPDATE kouzla SET pocet_kostek=1, typ_kostky='k8', pevny_bonus=0, vicenasobne=0 WHERE id=166 AND nazev='Sněhová koule' AND pocet_kostek IS NULL;
UPDATE kouzla SET pocet_kostek=1, typ_kostky='k10', pevny_bonus=5, vicenasobne=0 WHERE id=167 AND nazev='Ledové kopí' AND pocet_kostek IS NULL;
UPDATE kouzla SET pocet_kostek=1, typ_kostky='k6', pevny_bonus=4, vicenasobne=0 WHERE id=168 AND nazev='Rampouch' AND pocet_kostek IS NULL;
UPDATE kouzla SET pocet_kostek=1, typ_kostky='k6', pevny_bonus=2, vicenasobne=0 WHERE id=169 AND nazev='Ledovy dech' AND pocet_kostek IS NULL;
UPDATE kouzla SET pocet_kostek=1, typ_kostky='k6', pevny_bonus=2, vicenasobne=0 WHERE id=170 AND nazev='Ledová zbroj' AND pocet_kostek IS NULL;
UPDATE kouzla SET pocet_kostek=1, typ_kostky='k6', pevny_bonus=2, vicenasobne=0 WHERE id=171 AND nazev='Ledový štít' AND pocet_kostek IS NULL;
UPDATE kouzla SET pocet_kostek=4, typ_kostky='k10', pevny_bonus=0, vicenasobne=0 WHERE id=172 AND nazev='Ledové zrcadlo' AND pocet_kostek IS NULL;
UPDATE kouzla SET pocet_kostek=1, typ_kostky='k6', pevny_bonus=0, vicenasobne=0 WHERE id=174 AND nazev='Ledová tvorba-zbraň' AND pocet_kostek IS NULL;
UPDATE kouzla SET pocet_kostek=1, typ_kostky='k6', pevny_bonus=0, vicenasobne=0 WHERE id=177 AND nazev='Ledové vězení' AND pocet_kostek IS NULL;
UPDATE kouzla SET pocet_kostek=1, typ_kostky='k10', pevny_bonus=5, vicenasobne=0 WHERE id=179 AND nazev='Absolutní nula' AND pocet_kostek IS NULL;
UPDATE kouzla SET pocet_kostek=1, typ_kostky='k10', pevny_bonus=0, vicenasobne=0 WHERE id=180 AND nazev='Ohnivá střela' AND pocet_kostek IS NULL;
UPDATE kouzla SET pocet_kostek=1, typ_kostky='k4', pevny_bonus=2, vicenasobne=0 WHERE id=181 AND nazev='Duchové ohně' AND pocet_kostek IS NULL;
UPDATE kouzla SET pocet_kostek=1, typ_kostky='k6', pevny_bonus=1, vicenasobne=0 WHERE id=182 AND nazev='Ohnivý břit' AND pocet_kostek IS NULL;
UPDATE kouzla SET pocet_kostek=1, typ_kostky='k6', pevny_bonus=2, vicenasobne=0 WHERE id=183 AND nazev='Živá bomba' AND pocet_kostek IS NULL;
UPDATE kouzla SET pocet_kostek=1, typ_kostky='k6', pevny_bonus=0, vicenasobne=0 WHERE id=184 AND nazev='Fénixův plášť' AND pocet_kostek IS NULL;
UPDATE kouzla SET pocet_kostek=1, typ_kostky='k6', pevny_bonus=3, vicenasobne=0 WHERE id=185 AND nazev='Katapult' AND pocet_kostek IS NULL;
UPDATE kouzla SET pocet_kostek=2, typ_kostky='k8', pevny_bonus=2, vicenasobne=0 WHERE id=186 AND nazev='Ohnivá stěna' AND pocet_kostek IS NULL;
UPDATE kouzla SET pocet_kostek=3, typ_kostky='k6', pevny_bonus=6, vicenasobne=0 WHERE id=187 AND nazev='Spalující paprsek' AND pocet_kostek IS NULL;
UPDATE kouzla SET pocet_kostek=1, typ_kostky='k4', pevny_bonus=3, vicenasobne=0 WHERE id=188 AND nazev='Slzy slunce' AND pocet_kostek IS NULL;
UPDATE kouzla SET pocet_kostek=1, typ_kostky='k6', pevny_bonus=0, vicenasobne=0 WHERE id=189 AND nazev='Sloup ohně' AND pocet_kostek IS NULL;
UPDATE kouzla SET pocet_kostek=5, typ_kostky='k10', pevny_bonus=0, vicenasobne=0 WHERE id=191 AND nazev='Magma' AND pocet_kostek IS NULL;
UPDATE kouzla SET pocet_kostek=1, typ_kostky='k6', pevny_bonus=1, vicenasobne=0 WHERE id=199 AND nazev='Uzdrav lehká zranění' AND pocet_kostek IS NULL;
UPDATE kouzla SET pocet_kostek=2, typ_kostky='k6', pevny_bonus=2, vicenasobne=0 WHERE id=201 AND nazev='Uzdrav těžká zranění' AND pocet_kostek IS NULL;
UPDATE kouzla SET pocet_kostek=1, typ_kostky='k6', pevny_bonus=14, vicenasobne=0 WHERE id=206 AND nazev='Ošetři zranění chladem' AND pocet_kostek IS NULL;
UPDATE kouzla SET pocet_kostek=1, typ_kostky='k6', pevny_bonus=10, vicenasobne=0 WHERE id=207 AND nazev='Ošetři zranění kyselinou' AND pocet_kostek IS NULL;
UPDATE kouzla SET pocet_kostek=1, typ_kostky='k6', pevny_bonus=16, vicenasobne=0 WHERE id=208 AND nazev='Ošetři zranění ohněm' AND pocet_kostek IS NULL;
UPDATE kouzla SET pocet_kostek=1, typ_kostky='k6', pevny_bonus=1, vicenasobne=0 WHERE id=210 AND nazev='Úder varování' AND pocet_kostek IS NULL;
UPDATE kouzla SET pocet_kostek=2, typ_kostky='k6', pevny_bonus=2, vicenasobne=0 WHERE id=211 AND nazev='Úder zloby' AND pocet_kostek IS NULL;
UPDATE kouzla SET pocet_kostek=3, typ_kostky='k10', pevny_bonus=0, vicenasobne=0 WHERE id=212 AND nazev='Úder nenávisti' AND pocet_kostek IS NULL;
UPDATE kouzla SET pocet_kostek=1, typ_kostky='k6', pevny_bonus=0, vicenasobne=0 WHERE id=220 AND nazev='Odstranění únavy' AND pocet_kostek IS NULL;
UPDATE kouzla SET pocet_kostek=1, typ_kostky='k6', pevny_bonus=1, vicenasobne=0 WHERE id=230 AND nazev='Uzdrav lehká zranění' AND pocet_kostek IS NULL;
UPDATE kouzla SET pocet_kostek=2, typ_kostky='k6', pevny_bonus=2, vicenasobne=0 WHERE id=231 AND nazev='Uzdrav těžká zranění' AND pocet_kostek IS NULL;
UPDATE kouzla SET pocet_kostek=1, typ_kostky='k4', pevny_bonus=0, vicenasobne=0 WHERE id=240 AND nazev='Salva šípů' AND pocet_kostek IS NULL;
UPDATE kouzla SET pocet_kostek=4, typ_kostky='k10', pevny_bonus=0, vicenasobne=0 WHERE id=245 AND nazev='Smrtící šíp' AND pocet_kostek IS NULL;
UPDATE kouzla SET pocet_kostek=2, typ_kostky='k10', pevny_bonus=0, vicenasobne=0 WHERE id=272 AND nazev='Jedna mysl' AND pocet_kostek IS NULL;
UPDATE kouzla SET pocet_kostek=1, typ_kostky='k10', pevny_bonus=0, vicenasobne=0 WHERE id=281 AND nazev='Hněv lesa' AND pocet_kostek IS NULL;
UPDATE kouzla SET pocet_kostek=4, typ_kostky='k6', pevny_bonus=6, vicenasobne=0 WHERE id=288 AND nazev='Pouto lásky' AND pocet_kostek IS NULL;
UPDATE kouzla SET pocet_kostek=1, typ_kostky='k10', pevny_bonus=0, vicenasobne=0 WHERE id=296 AND nazev='Posílení kouzel' AND pocet_kostek IS NULL;
UPDATE kouzla SET pocet_kostek=1, typ_kostky='k6', pevny_bonus=0, vicenasobne=0 WHERE id=308 AND nazev='Nenávist lesa' AND pocet_kostek IS NULL;
UPDATE kouzla SET pocet_kostek=1, typ_kostky='k6', pevny_bonus=1, vicenasobne=0 WHERE id=333 AND nazev='Ledová čepel' AND pocet_kostek IS NULL;
UPDATE kouzla SET pocet_kostek=1, typ_kostky='k10', pevny_bonus=0, vicenasobne=0 WHERE id=339 AND nazev='Trojitý sek' AND pocet_kostek IS NULL;
UPDATE kouzla SET pocet_kostek=1, typ_kostky='k4', pevny_bonus=0, vicenasobne=0 WHERE id=367 AND nazev='Staccato 1' AND pocet_kostek IS NULL;
UPDATE kouzla SET pocet_kostek=1, typ_kostky='k4', pevny_bonus=0, vicenasobne=0 WHERE id=368 AND nazev='Legato 2' AND pocet_kostek IS NULL;
UPDATE kouzla SET pocet_kostek=1, typ_kostky='k6', pevny_bonus=4, vicenasobne=0 WHERE id=373 AND nazev='Trapný fórky' AND pocet_kostek IS NULL;
UPDATE kouzla SET pocet_kostek=1, typ_kostky='k4', pevny_bonus=0, vicenasobne=0 WHERE id=374 AND nazev='Kvintakord' AND pocet_kostek IS NULL;
UPDATE kouzla SET pocet_kostek=1, typ_kostky='k4', pevny_bonus=0, vicenasobne=0 WHERE id=379 AND nazev='Brutální zesměšnění' AND pocet_kostek IS NULL;
UPDATE kouzla SET pocet_kostek=1, typ_kostky='k6', pevny_bonus=0, vicenasobne=0 WHERE id=380 AND nazev='Brnkání na nervy 1' AND pocet_kostek IS NULL;
UPDATE kouzla SET pocet_kostek=2, typ_kostky='k6', pevny_bonus=0, vicenasobne=0 WHERE id=381 AND nazev='Otravná melodie 2' AND pocet_kostek IS NULL;
UPDATE kouzla SET pocet_kostek=2, typ_kostky='k10', pevny_bonus=2, vicenasobne=0 WHERE id=382 AND nazev='Zdrcující znělka 3' AND pocet_kostek IS NULL;
UPDATE kouzla SET pocet_kostek=3, typ_kostky='k10', pevny_bonus=6, vicenasobne=0 WHERE id=383 AND nazev='Lamač srdcí 4' AND pocet_kostek IS NULL;
UPDATE kouzla SET pocet_kostek=1, typ_kostky='k6', pevny_bonus=0, vicenasobne=0 WHERE id=390 AND nazev='Ochrana múz' AND pocet_kostek IS NULL;
UPDATE kouzla SET pocet_kostek=2, typ_kostky='k6', pevny_bonus=0, vicenasobne=0 WHERE id=392 AND nazev='Hromový hlas' AND pocet_kostek IS NULL;
UPDATE kouzla SET pocet_kostek=1, typ_kostky='k6', pevny_bonus=0, vicenasobne=0 WHERE id=393 AND nazev='Stěna zvuku' AND pocet_kostek IS NULL;
UPDATE kouzla SET pocet_kostek=1, typ_kostky='k10', pevny_bonus=0, vicenasobne=0 WHERE id=394 AND nazev='Píseň osudu' AND pocet_kostek IS NULL;
UPDATE kouzla SET pocet_kostek=1, typ_kostky='k10', pevny_bonus=0, vicenasobne=0 WHERE id=396 AND nazev='Hromada' AND pocet_kostek IS NULL;
UPDATE kouzla SET pocet_kostek=3, typ_kostky='k10', pevny_bonus=10, vicenasobne=0 WHERE id=398 AND nazev='Nespokojené publikum' AND pocet_kostek IS NULL;
UPDATE kouzla SET pocet_kostek=1, typ_kostky='k6', pevny_bonus=2, vicenasobne=0 WHERE id=405 AND nazev='Kyselá slova' AND pocet_kostek IS NULL;
UPDATE kouzla SET pocet_kostek=1, typ_kostky='k4', pevny_bonus=0, vicenasobne=0 WHERE id=407 AND nazev='Deptající pochybnosti' AND pocet_kostek IS NULL;
UPDATE kouzla SET pocet_kostek=1, typ_kostky='k10', pevny_bonus=0, vicenasobne=0 WHERE id=412 AND nazev='Drill seržant' AND pocet_kostek IS NULL;
UPDATE kouzla SET pocet_kostek=1, typ_kostky='k4', pevny_bonus=3, vicenasobne=0 WHERE id=424 AND nazev='Živá voda' AND pocet_kostek IS NULL;
UPDATE kouzla SET pocet_kostek=1, typ_kostky='k4', pevny_bonus=0, vicenasobne=0 WHERE id=426 AND nazev='Zvukový výboj' AND pocet_kostek IS NULL;
UPDATE kouzla SET pocet_kostek=1, typ_kostky='k4', pevny_bonus=0, vicenasobne=0 WHERE id=427 AND nazev='Záštiplná múza' AND pocet_kostek IS NULL;
UPDATE kouzla SET pocet_kostek=1, typ_kostky='k6', pevny_bonus=4, vicenasobne=0 WHERE id=493 AND nazev='Zasloužený odpočinek' AND pocet_kostek IS NULL;
UPDATE kouzla SET pocet_kostek=1, typ_kostky='k10', pevny_bonus=5, vicenasobne=0 WHERE id=500 AND nazev='Zloba kamene' AND pocet_kostek IS NULL;
UPDATE kouzla SET pocet_kostek=2, typ_kostky='k10', pevny_bonus=10, vicenasobne=0 WHERE id=501 AND nazev='Zuřivost kamene' AND pocet_kostek IS NULL;
UPDATE kouzla SET pocet_kostek=1, typ_kostky='k10', pevny_bonus=5, vicenasobne=0 WHERE id=502 AND nazev='Kamenná bouře' AND pocet_kostek IS NULL;
UPDATE kouzla SET pocet_kostek=2, typ_kostky='k6', pevny_bonus=2, vicenasobne=0 WHERE id=503 AND nazev='Kamenná zahrada' AND pocet_kostek IS NULL;
UPDATE kouzla SET pocet_kostek=1, typ_kostky='k6', pevny_bonus=1, vicenasobne=0 WHERE id=506 AND nazev='Verš ohně I' AND pocet_kostek IS NULL;
UPDATE kouzla SET pocet_kostek=2, typ_kostky='k6', pevny_bonus=2, vicenasobne=0 WHERE id=507 AND nazev='Verš ohně II' AND pocet_kostek IS NULL;
UPDATE kouzla SET pocet_kostek=3, typ_kostky='k6', pevny_bonus=3, vicenasobne=0 WHERE id=508 AND nazev='Verš ohně III' AND pocet_kostek IS NULL;
UPDATE kouzla SET pocet_kostek=1, typ_kostky='k10', pevny_bonus=0, vicenasobne=0 WHERE id=511 AND nazev='Plamen života' AND pocet_kostek IS NULL;
UPDATE kouzla SET pocet_kostek=1, typ_kostky='k6', pevny_bonus=2, vicenasobne=0 WHERE id=512 AND nazev='Dech větru' AND pocet_kostek IS NULL;
UPDATE kouzla SET pocet_kostek=2, typ_kostky='k10', pevny_bonus=6, vicenasobne=0 WHERE id=514 AND nazev='Lávová dlaň' AND pocet_kostek IS NULL;
UPDATE kouzla SET pocet_kostek=3, typ_kostky='k10', pevny_bonus=4, vicenasobne=0 WHERE id=515 AND nazev='Lávová pěst' AND pocet_kostek IS NULL;
UPDATE kouzla SET pocet_kostek=4, typ_kostky='k10', pevny_bonus=2, vicenasobne=0 WHERE id=516 AND nazev='Titánská pěst' AND pocet_kostek IS NULL;
UPDATE kouzla SET pocet_kostek=1, typ_kostky='k4', pevny_bonus=0, vicenasobne=0 WHERE id=521 AND nazev='Sláva zesnulých' AND pocet_kostek IS NULL;
UPDATE kouzla SET pocet_kostek=1, typ_kostky='k6', pevny_bonus=0, vicenasobne=0 WHERE id=522 AND nazev='Hlodající vina' AND pocet_kostek IS NULL;
UPDATE kouzla SET pocet_kostek=1, typ_kostky='k8', pevny_bonus=0, vicenasobne=0 WHERE id=523 AND nazev='Soud předků' AND pocet_kostek IS NULL;
UPDATE kouzla SET pocet_kostek=1, typ_kostky='k10', pevny_bonus=0, vicenasobne=0 WHERE id=543 AND nazev='Runa Síry III' AND pocet_kostek IS NULL;
UPDATE kouzla SET pocet_kostek=1, typ_kostky='k10', pevny_bonus=0, vicenasobne=0 WHERE id=544 AND nazev='Runa Zničení I' AND pocet_kostek IS NULL;
UPDATE kouzla SET pocet_kostek=2, typ_kostky='k10', pevny_bonus=0, vicenasobne=0 WHERE id=545 AND nazev='Runa Zničení II' AND pocet_kostek IS NULL;
UPDATE kouzla SET pocet_kostek=3, typ_kostky='k10', pevny_bonus=0, vicenasobne=0 WHERE id=546 AND nazev='Runa Zničení III' AND pocet_kostek IS NULL;
UPDATE kouzla SET pocet_kostek=1, typ_kostky='k4', pevny_bonus=1, vicenasobne=0 WHERE id=552 AND nazev='Runa Oběti I' AND pocet_kostek IS NULL;
UPDATE kouzla SET pocet_kostek=1, typ_kostky='k6', pevny_bonus=2, vicenasobne=0 WHERE id=553 AND nazev='Runa Oběti II' AND pocet_kostek IS NULL;
UPDATE kouzla SET pocet_kostek=1, typ_kostky='k8', pevny_bonus=3, vicenasobne=0 WHERE id=554 AND nazev='Runa Oběti III' AND pocet_kostek IS NULL;
UPDATE kouzla SET pocet_kostek=1, typ_kostky='k4', pevny_bonus=1, vicenasobne=0 WHERE id=555 AND nazev='Runa Lékárníka I' AND pocet_kostek IS NULL;
UPDATE kouzla SET pocet_kostek=1, typ_kostky='k6', pevny_bonus=2, vicenasobne=0 WHERE id=556 AND nazev='Runa Lékárníka II' AND pocet_kostek IS NULL;
UPDATE kouzla SET pocet_kostek=1, typ_kostky='k8', pevny_bonus=3, vicenasobne=0 WHERE id=557 AND nazev='Runa Lékárníka III' AND pocet_kostek IS NULL;
UPDATE kouzla SET pocet_kostek=1, typ_kostky='k10', pevny_bonus=0, vicenasobne=0 WHERE id=558 AND nazev='Runa Slunce I' AND pocet_kostek IS NULL;
UPDATE kouzla SET pocet_kostek=2, typ_kostky='k10', pevny_bonus=0, vicenasobne=0 WHERE id=559 AND nazev='Runa Slunce II' AND pocet_kostek IS NULL;
UPDATE kouzla SET pocet_kostek=3, typ_kostky='k10', pevny_bonus=0, vicenasobne=0 WHERE id=560 AND nazev='Runa Slunce III' AND pocet_kostek IS NULL;
UPDATE kouzla SET pocet_kostek=3, typ_kostky='k6', pevny_bonus=6, vicenasobne=0 WHERE id=613 AND nazev='Urgentní léčba' AND pocet_kostek IS NULL;
UPDATE kouzla SET pocet_kostek=2, typ_kostky='k6', pevny_bonus=6, vicenasobne=0 WHERE id=639 AND nazev='Rychlý úder' AND pocet_kostek IS NULL;
UPDATE kouzla SET pocet_kostek=1, typ_kostky='k6', pevny_bonus=2, vicenasobne=0 WHERE id=641 AND nazev='Temná čepel' AND pocet_kostek IS NULL;
UPDATE kouzla SET pocet_kostek=1, typ_kostky='k4', pevny_bonus=2, vicenasobne=0 WHERE id=651 AND nazev='Světlonoš' AND pocet_kostek IS NULL;
UPDATE kouzla SET pocet_kostek=1, typ_kostky='k6', pevny_bonus=0, vicenasobne=0 WHERE id=652 AND nazev='Dlouhý dech' AND pocet_kostek IS NULL;
UPDATE kouzla SET pocet_kostek=2, typ_kostky='k6', pevny_bonus=2, vicenasobne=0 WHERE id=653 AND nazev='Temná čepel' AND pocet_kostek IS NULL;
UPDATE kouzla SET pocet_kostek=2, typ_kostky='k4', pevny_bonus=4, vicenasobne=0 WHERE id=658 AND nazev='Světlonoš (16. úroveň)' AND pocet_kostek IS NULL;
UPDATE kouzla SET pocet_kostek=1, typ_kostky='k6', pevny_bonus=3, vicenasobne=0 WHERE id=666 AND nazev='Temná ektoplazma' AND pocet_kostek IS NULL;
UPDATE kouzla SET pocet_kostek=1, typ_kostky='k6', pevny_bonus=2, vicenasobne=0 WHERE id=667 AND nazev='Lože ostnů' AND pocet_kostek IS NULL;
UPDATE kouzla SET pocet_kostek=1, typ_kostky='k10', pevny_bonus=0, vicenasobne=0 WHERE id=672 AND nazev='Stínový válečník' AND pocet_kostek IS NULL;
UPDATE kouzla SET pocet_kostek=1, typ_kostky='k10', pevny_bonus=1, vicenasobne=0 WHERE id=673 AND nazev='Stínový střelec' AND pocet_kostek IS NULL;
UPDATE kouzla SET pocet_kostek=1, typ_kostky='k10', pevny_bonus=0, vicenasobne=0 WHERE id=674 AND nazev='Dusivý stín' AND pocet_kostek IS NULL;
UPDATE kouzla SET pocet_kostek=4, typ_kostky='k6', pevny_bonus=8, vicenasobne=0 WHERE id=675 AND nazev='Zuby noci' AND pocet_kostek IS NULL;
UPDATE kouzla SET pocet_kostek=1, typ_kostky='k4', pevny_bonus=0, vicenasobne=0 WHERE id=676 AND nazev='Bestie' AND pocet_kostek IS NULL;
UPDATE kouzla SET pocet_kostek=1, typ_kostky='k6', pevny_bonus=1, vicenasobne=0 WHERE id=679 AND nazev='Gravitační studna' AND pocet_kostek IS NULL;
UPDATE kouzla SET pocet_kostek=4, typ_kostky='k6', pevny_bonus=3, vicenasobne=0 WHERE id=680 AND nazev='Temný lék' AND pocet_kostek IS NULL;
UPDATE kouzla SET pocet_kostek=3, typ_kostky='k6', pevny_bonus=13, vicenasobne=0 WHERE id=681 AND nazev='Drtivá noc' AND pocet_kostek IS NULL;
UPDATE kouzla SET pocet_kostek=1, typ_kostky='k4', pevny_bonus=0, vicenasobne=0 WHERE id=682 AND nazev='Noční můra' AND pocet_kostek IS NULL;
UPDATE kouzla SET pocet_kostek=3, typ_kostky='k6', pevny_bonus=4, vicenasobne=0 WHERE id=686 AND nazev='Černá liška' AND pocet_kostek IS NULL;
UPDATE kouzla SET pocet_kostek=1, typ_kostky='k6', pevny_bonus=3, vicenasobne=0 WHERE id=687 AND nazev='Slovo moci' AND pocet_kostek IS NULL;
UPDATE kouzla SET pocet_kostek=6, typ_kostky='k6', pevny_bonus=0, vicenasobne=0 WHERE id=688 AND nazev='Tichá brána' AND pocet_kostek IS NULL;
UPDATE kouzla SET pocet_kostek=2, typ_kostky='k6', pevny_bonus=4, vicenasobne=0 WHERE id=689 AND nazev='Černá hvězda' AND pocet_kostek IS NULL;
UPDATE kouzla SET pocet_kostek=1, typ_kostky='k10', pevny_bonus=0, vicenasobne=0 WHERE id=690 AND nazev='Zlotos' AND pocet_kostek IS NULL;
UPDATE kouzla SET pocet_kostek=6, typ_kostky='k6', pevny_bonus=12, vicenasobne=0 WHERE id=691 AND nazev='Zuby noci 16. úroveň' AND pocet_kostek IS NULL;
UPDATE kouzla SET pocet_kostek=1, typ_kostky='k6', pevny_bonus=2, vicenasobne=0 WHERE id=693 AND nazev='Lože ostnů 16. úroveň' AND pocet_kostek IS NULL;
UPDATE kouzla SET pocet_kostek=2, typ_kostky='k10', pevny_bonus=6, vicenasobne=0 WHERE id=698 AND nazev='Elixír Démonní krve - působení 6. úroveň' AND pocet_kostek IS NULL;
UPDATE kouzla SET pocet_kostek=1, typ_kostky='k4', pevny_bonus=1, vicenasobne=0 WHERE id=725 AND nazev='Ohnivý dotek' AND pocet_kostek IS NULL;
UPDATE kouzla SET pocet_kostek=1, typ_kostky='k4', pevny_bonus=1, vicenasobne=0 WHERE id=726 AND nazev='Vyleč nepatrná zranění' AND pocet_kostek IS NULL;
UPDATE kouzla SET pocet_kostek=1, typ_kostky='k6', pevny_bonus=1, vicenasobne=0 WHERE id=729 AND nazev='Úder varování' AND pocet_kostek IS NULL;
UPDATE kouzla SET pocet_kostek=1, typ_kostky='k6', pevny_bonus=0, vicenasobne=0 WHERE id=756 AND nazev='Odvracení nemrtvých' AND pocet_kostek IS NULL;
UPDATE kouzla SET pocet_kostek=1, typ_kostky='k6', pevny_bonus=0, vicenasobne=0 WHERE id=757 AND nazev='Přivolání nemrtvých' AND pocet_kostek IS NULL;
UPDATE kouzla SET pocet_kostek=1, typ_kostky='k4', pevny_bonus=0, vicenasobne=0 WHERE id=758 AND nazev='Požehnání' AND pocet_kostek IS NULL;
UPDATE kouzla SET pocet_kostek=1, typ_kostky='k6', pevny_bonus=0, vicenasobne=0 WHERE id=760 AND nazev='Zlaté kopí' AND pocet_kostek IS NULL;
UPDATE kouzla SET pocet_kostek=1, typ_kostky='k6', pevny_bonus=0, vicenasobne=0 WHERE id=761 AND nazev='Obsidiánové kopí' AND pocet_kostek IS NULL;
UPDATE kouzla SET pocet_kostek=2, typ_kostky='k6', pevny_bonus=4, vicenasobne=0 WHERE id=762 AND nazev='Vlna života' AND pocet_kostek IS NULL;
UPDATE kouzla SET pocet_kostek=2, typ_kostky='k6', pevny_bonus=4, vicenasobne=0 WHERE id=763 AND nazev='Vlna smrti' AND pocet_kostek IS NULL;
UPDATE kouzla SET pocet_kostek=2, typ_kostky='k10', pevny_bonus=10, vicenasobne=0 WHERE id=765 AND nazev='Požehnání těla' AND pocet_kostek IS NULL;
UPDATE kouzla SET pocet_kostek=1, typ_kostky='k8', pevny_bonus=0, vicenasobne=0 WHERE id=768 AND nazev='Posvátný plamen' AND pocet_kostek IS NULL;
UPDATE kouzla SET pocet_kostek=3, typ_kostky='k10', pevny_bonus=0, vicenasobne=0 WHERE id=770 AND nazev='Sluneční paprsek' AND pocet_kostek IS NULL;
UPDATE kouzla SET pocet_kostek=3, typ_kostky='k10', pevny_bonus=0, vicenasobne=0 WHERE id=771 AND nazev='Měsíční paprsek' AND pocet_kostek IS NULL;
UPDATE kouzla SET pocet_kostek=1, typ_kostky='k6', pevny_bonus=0, vicenasobne=0 WHERE id=775 AND nazev='Zatracení' AND pocet_kostek IS NULL;
UPDATE kouzla SET pocet_kostek=3, typ_kostky='k10', pevny_bonus=3, vicenasobne=0 WHERE id=776 AND nazev='Ošetři kritická zranění' AND pocet_kostek IS NULL;
UPDATE kouzla SET pocet_kostek=1, typ_kostky='k4', pevny_bonus=0, vicenasobne=0 WHERE id=778 AND nazev='Posvěcená půda' AND pocet_kostek IS NULL;
UPDATE kouzla SET pocet_kostek=1, typ_kostky='k4', pevny_bonus=0, vicenasobne=0 WHERE id=779 AND nazev='Prokletá půda' AND pocet_kostek IS NULL;
UPDATE kouzla SET pocet_kostek=2, typ_kostky='k10', pevny_bonus=0, vicenasobne=0 WHERE id=785 AND nazev='Nebeský oheň' AND pocet_kostek IS NULL;
UPDATE kouzla SET pocet_kostek=3, typ_kostky='k10', pevny_bonus=0, vicenasobne=0 WHERE id=786 AND nazev='Pekelný oheň' AND pocet_kostek IS NULL;
UPDATE kouzla SET pocet_kostek=1, typ_kostky='k4', pevny_bonus=1, vicenasobne=0 WHERE id=787 AND nazev='Strážné duše' AND pocet_kostek IS NULL;
UPDATE kouzla SET pocet_kostek=1, typ_kostky='k10', pevny_bonus=0, vicenasobne=0 WHERE id=788 AND nazev='Avatar světla' AND pocet_kostek IS NULL;
UPDATE kouzla SET pocet_kostek=1, typ_kostky='k10', pevny_bonus=0, vicenasobne=0 WHERE id=789 AND nazev='Avatar temnoty' AND pocet_kostek IS NULL;
UPDATE kouzla SET pocet_kostek=6, typ_kostky='k6', pevny_bonus=5, vicenasobne=0 WHERE id=791 AND nazev='Darování života' AND pocet_kostek IS NULL;
UPDATE kouzla SET pocet_kostek=1, typ_kostky='k6', pevny_bonus=0, vicenasobne=0 WHERE id=819 AND nazev='Odvracení nemrtvých' AND pocet_kostek IS NULL;
UPDATE kouzla SET pocet_kostek=1, typ_kostky='k6', pevny_bonus=0, vicenasobne=0 WHERE id=820 AND nazev='Přivolání nemrtvých' AND pocet_kostek IS NULL;
UPDATE kouzla SET pocet_kostek=1, typ_kostky='k4', pevny_bonus=0, vicenasobne=0 WHERE id=821 AND nazev='Požehnání' AND pocet_kostek IS NULL;
UPDATE kouzla SET pocet_kostek=1, typ_kostky='k10', pevny_bonus=0, vicenasobne=0 WHERE id=822 AND nazev='Kletba' AND pocet_kostek IS NULL;
UPDATE kouzla SET pocet_kostek=1, typ_kostky='k6', pevny_bonus=2, vicenasobne=0 WHERE id=824 AND nazev='Napuštění mocí' AND pocet_kostek IS NULL;
UPDATE kouzla SET pocet_kostek=2, typ_kostky='k6', pevny_bonus=4, vicenasobne=0 WHERE id=825 AND nazev='Vlna moci' AND pocet_kostek IS NULL;
UPDATE kouzla SET pocet_kostek=1, typ_kostky='k6', pevny_bonus=0, vicenasobne=0 WHERE id=828 AND nazev='Zadrž osobu' AND pocet_kostek IS NULL;
UPDATE kouzla SET pocet_kostek=3, typ_kostky='k10', pevny_bonus=0, vicenasobne=0 WHERE id=831 AND nazev='Paprsek' AND pocet_kostek IS NULL;
UPDATE kouzla SET pocet_kostek=1, typ_kostky='k4', pevny_bonus=0, vicenasobne=0 WHERE id=835 AND nazev='Svatyně' AND pocet_kostek IS NULL;
UPDATE kouzla SET pocet_kostek=1, typ_kostky='k6', pevny_bonus=0, vicenasobne=0 WHERE id=841 AND nazev='Plamen z nebes' AND pocet_kostek IS NULL;
UPDATE kouzla SET pocet_kostek=1, typ_kostky='k20', pevny_bonus=0, vicenasobne=0 WHERE id=844 AND nazev='Verbum vitae' AND pocet_kostek IS NULL;
UPDATE kouzla SET pocet_kostek=1, typ_kostky='k20', pevny_bonus=0, vicenasobne=0 WHERE id=846 AND nazev='Sub protectione Patris' AND pocet_kostek IS NULL;
UPDATE kouzla SET pocet_kostek=1, typ_kostky='k6', pevny_bonus=0, vicenasobne=0 WHERE id=847 AND nazev='Mortuus fuerit, Vivet' AND pocet_kostek IS NULL;
UPDATE kouzla SET pocet_kostek=1, typ_kostky='k6', pevny_bonus=0, vicenasobne=0 WHERE id=848 AND nazev='Incarnatus' AND pocet_kostek IS NULL;
UPDATE kouzla SET pocet_kostek=1, typ_kostky='k6', pevny_bonus=3, vicenasobne=0 WHERE id=849 AND nazev='Angel de la guarda' AND pocet_kostek IS NULL;
UPDATE kouzla SET pocet_kostek=1, typ_kostky='k6', pevny_bonus=6, vicenasobne=0 WHERE id=850 AND nazev='Spiritus domini' AND pocet_kostek IS NULL;
UPDATE kouzla SET pocet_kostek=1, typ_kostky='k6', pevny_bonus=9, vicenasobne=0 WHERE id=851 AND nazev='Facies dei' AND pocet_kostek IS NULL;
UPDATE kouzla SET pocet_kostek=1, typ_kostky='k6', pevny_bonus=12, vicenasobne=0 WHERE id=852 AND nazev='Deus manifestatus in carne' AND pocet_kostek IS NULL;
UPDATE kouzla SET pocet_kostek=1, typ_kostky='k4', pevny_bonus=2, vicenasobne=0 WHERE id=883 AND nazev='Potrava pro tělo i duši' AND pocet_kostek IS NULL;
UPDATE kouzla SET pocet_kostek=1, typ_kostky='k8', pevny_bonus=0, vicenasobne=0 WHERE id=886 AND nazev='Flagelant' AND pocet_kostek IS NULL;
UPDATE kouzla SET pocet_kostek=1, typ_kostky='k6', pevny_bonus=0, vicenasobne=0 WHERE id=888 AND nazev='zuřivost' AND pocet_kostek IS NULL;
UPDATE kouzla SET pocet_kostek=1, typ_kostky='k6', pevny_bonus=0, vicenasobne=0 WHERE id=890 AND nazev='regenerace' AND pocet_kostek IS NULL;
UPDATE kouzla SET pocet_kostek=1, typ_kostky='k6', pevny_bonus=0, vicenasobne=0 WHERE id=902 AND nazev='Planoucí démon' AND pocet_kostek IS NULL;
UPDATE kouzla SET pocet_kostek=1, typ_kostky='k6', pevny_bonus=0, vicenasobne=0 WHERE id=928 AND nazev='Sopka' AND pocet_kostek IS NULL;
UPDATE kouzla SET pocet_kostek=3, typ_kostky='k6', pevny_bonus=0, vicenasobne=0 WHERE id=929 AND nazev='Tornádo' AND pocet_kostek IS NULL;
UPDATE kouzla SET pocet_kostek=5, typ_kostky='k6', pevny_bonus=0, vicenasobne=0 WHERE id=930 AND nazev='Zemětřesení' AND pocet_kostek IS NULL;
UPDATE kouzla SET pocet_kostek=1, typ_kostky='k6', pevny_bonus=0, vicenasobne=0 WHERE id=931 AND nazev='Tsunami' AND pocet_kostek IS NULL;
UPDATE kouzla SET pocet_kostek=1, typ_kostky='k6', pevny_bonus=0, vicenasobne=0 WHERE id=932 AND nazev='Hurikán' AND pocet_kostek IS NULL;
UPDATE kouzla SET pocet_kostek=1, typ_kostky='k6', pevny_bonus=0, vicenasobne=0 WHERE id=934 AND nazev='Pramen' AND pocet_kostek IS NULL;
UPDATE kouzla SET pocet_kostek=10, typ_kostky='k10', pevny_bonus=0, vicenasobne=0 WHERE id=935 AND nazev='Láva' AND pocet_kostek IS NULL;
UPDATE kouzla SET pocet_kostek=1, typ_kostky='k6', pevny_bonus=0, vicenasobne=0 WHERE id=936 AND nazev='Gejzír' AND pocet_kostek IS NULL;
UPDATE kouzla SET pocet_kostek=1, typ_kostky='k6', pevny_bonus=0, vicenasobne=0 WHERE id=940 AND nazev='Požár' AND pocet_kostek IS NULL;
UPDATE kouzla SET pocet_kostek=10, typ_kostky='k10', pevny_bonus=0, vicenasobne=0 WHERE id=942 AND nazev='Krakatoa' AND pocet_kostek IS NULL;
UPDATE kouzla SET pocet_kostek=1, typ_kostky='k6', pevny_bonus=0, vicenasobne=0 WHERE id=944 AND nazev='Ohnivý ďábel' AND pocet_kostek IS NULL;
UPDATE kouzla SET pocet_kostek=1, typ_kostky='k10', pevny_bonus=0, vicenasobne=0 WHERE id=945 AND nazev='Kamená slupka' AND pocet_kostek IS NULL;
UPDATE kouzla SET pocet_kostek=1, typ_kostky='k10', pevny_bonus=0, vicenasobne=0 WHERE id=946 AND nazev='Obnova' AND pocet_kostek IS NULL;
UPDATE kouzla SET pocet_kostek=1, typ_kostky='k6', pevny_bonus=0, vicenasobne=0 WHERE id=948 AND nazev='Hromosvod' AND pocet_kostek IS NULL;
UPDATE kouzla SET pocet_kostek=4, typ_kostky='k6', pevny_bonus=0, vicenasobne=0 WHERE id=950 AND nazev='Řetězový blesk' AND pocet_kostek IS NULL;
UPDATE kouzla SET pocet_kostek=2, typ_kostky='k10', pevny_bonus=0, vicenasobne=0 WHERE id=953 AND nazev='Bleskový přesun' AND pocet_kostek IS NULL;
