name: FTP Deploy

on:
  push:
    branches: [main]

jobs:
  deploy:
    name: Deploy to FTP hosting
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 2

      - name: FTP Deploy
        uses: SamKirkland/FTP-Deploy-Action@v4.3.5
        with:
          server: ${{ secrets.FTP_SERVER }}
          username: ${{ secrets.FTP_USERNAME }}
          password: ${{ secrets.FTP_PASSWORD }}
          protocol: ftps
          server-dir: ./
          dry-run: true
          exclude: |
            **/.git*
            **/.git*/**
            .github/**
            **/*.md
            node_modules/**
